name: Publish to npm
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm publish
      run: |
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        npm install
        npm test
        npm publish
      env:
        CI: true
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
